### ISSUE TITLE
Operator Feature Request | Disable permissions for node-level metrics and logs in wandb-console

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/operator#19] opened 2024-08-28 18:54 UTC

**Comment by vijay-wandb** [comment] 2024-08-28 19:08
Problem:
Following resources are currently removed in FORD's enviornment

metadata:
  name: wandb-manager-role
rules:
 - apiGroups:
    - ""
    resources:
    - ingresses
    - nodes
    - nodes/metrics
    - nodes/spec
    - nodes/stats
    - nodes/proxy
    - namespaces
    verbs:
    - get
    - list
    - watch

In environments like FORD, where node metrics should not be exposed to the `wandb-manager-role,` the wandb-console component's attempt to collect node information results in RBAC permission errors.

FailedGetResourceMetric:
Failed to get CPU utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)

Expected Outcome:
When this option is enabled, the `wandb-console `should no longer attempt to collect or display node-level metrics. This will ensure that the Operator functions correctly in environments where node information is restricted

**Comment by abhinavg6** [comment] 2024-09-12 14:09
@vijay-wandb - Can you please clarify the issue in this request as per the discussion in this week's operator meeting?

**Comment by vijay-wandb** [comment] 2024-09-16 15:18
@abhinavg6 
I have updated the request

**Comment by abhinavg6** [comment] 2024-09-16 15:58
As per @danielpanzella - we can remove these permissions from the console as these are not used. Console uses prometheus to get the required data.

**Comment by vijay-wandb** [comment] 2024-09-30 15:10
ClusterRole `wandb-otel-daemonset` requires access to `nodes/spec, nodes, nodes/stat`

`{"level":"error","ts":"2024-09-30T14:59:41Z","msg":"Failed to apply config changes.","controller":"weightsandbiases","controllerGroup":"apps.wandb.com","controllerKind":"WeightsAndBiases","WeightsAndBiases":{"name":"wandb","namespace":"test2"},"namespace":"test2","name":"wandb","reconcileID":"f81d3c25-5c7c-4789-8ca9-18880416623f","error":"clusterroles.rbac.authorization.k8s.io \"wandb-otel-daemonset\" is forbidden: user \"system:serviceaccount:test2:wandb-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:test2\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"nodes\"], Verbs:[\"get\" \"list\" \"watch\"]}\n{APIGroups:[\"\"], Resources:[\"nodes/spec\"], Verbs:[\"get\" \"list\" \"watch\"]}\n{APIGroups:[\"\"], Resources:[\"nodes/stats\"], Verbs:[\"get\" \"watch\" \"list\"]}","stacktrace":"github.com/wandb/operator/controllers.(*WeightsAndBiasesReconciler).Reconcile\n\t/workspace/controllers/weightsandbiases_controller.go:249\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}`

**Comment by abhinavg6** [comment] 2024-09-30 15:41
Vijay to retest after disabling the Otel on the cluster

**Comment by abhinavg6** [comment] 2024-10-01 12:06
@vijay-wandb - Were you able to retest?

**Comment by vijay-wandb** [comment] 2024-10-02 20:28
@abhinavg6 @velotioaastha 

I tested with otel disabled, which as expected, resolved the previous error message about ClusterRole `wandb-otel-daemonset ` needing access to `nodes/spec, nodes, nodes/stat`

However `wandb-console` still requires access to `nodes` resource. Error message below.

`{"level":"error","ts":"2024-10-02T20:17:47Z","msg":"Failed to apply config changes.","controller":"weightsandbiases","controllerGroup":"apps.wandb.com","controllerKind":"WeightsAndBiases","WeightsAndBiases":{"name":"wandb","namespace":"test4"},"namespace":"test4","name":"wandb","reconcileID":"45154c66-1f24-4ae7-96f0-11db9712dd5f","error":"clusterroles.rbac.authorization.k8s.io \"wandb-console\" is forbidden: user \"system:serviceaccount:test4:wandb-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:test4\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"nodes\"], Verbs:[\"get\" \"list\"]}","stacktrace":"github.com/wandb/operator/controllers.(*WeightsAndBiasesReconciler).Reconcile\n\t/workspace/controllers/weightsandbiases_controller.go:249\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}`

**Comment by abhinavg6** [comment] 2024-10-02 20:49
@vijay-wandb - Are you testing with the latest, like operator-wandb chart 0.18.1+?

**Comment by vijay-wandb** [comment] 2024-10-02 22:20
I tested with the most recent `Operator v1.14.0.`..those errors are from the operator log, so the issue has to do with `operator` not `operator-wandb`

```
vijayp@Vijay-Panneerselvam-MR6QDWQJ3V test4 % k get pod wandb-controller-manager-69d558d5fb-89x4x -o yaml | grep -i "sha256"
    imageID: docker.io/wandb/controller@sha256:5505566eceb90fb208d97021e8a1157d7546ad31ed3937b19944891de300110f
```


![image](https://github.com/user-attachments/assets/0c64523e-e294-4dcc-bbbd-de292167567d)

**Comment by velotioaastha** [comment] 2024-10-03 11:49
> operator-wandb

hey @vijay-wandb , so you mean we need access to nodes resource. That. means, we have to revert this [PR](https://github.com/wandb/helm-charts/pull/219/files) changes.

**Comment by vijay-wandb** [comment] 2024-10-03 13:10
No, that is not what I'm saying. `wandb-console` should not require access to `nodes` resource. According to Daniel, console uses prometheus to get the neccessary data.

To meet a customer need, I removed the following resources from the `wandb-manager-role` role which seems to be propagated to 'wandb-console' role. We shouldn't see the error, as console shouldn't need access to `nodes` resource.

Here are the removed resources:
```
    - nodes
    - nodes/metrics
    - nodes/spec
    - nodes/stats
    - nodes/proxy
```

` \"wandb-console\" is forbidden: user \"system:serviceaccount:test4:wandb-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:test4\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"nodes\"], Verbs:[\"get\" \"list\"]}",`

**Comment by abhinavg6** [comment] 2024-10-03 13:41
cc @danielpanzella if you've thoughts on this?

**Comment by amanpruthi** [comment] 2024-10-07 08:09
Hi @vijay-wandb ,

So far we tried below things 

Steps :

1. Deployed test cluster and helm charts
2. Edited wandb-manager-role  Clusterrole by removing below permission and restarted wandb-controller

`  - nodes
    - nodes/metrics
    - nodes/spec
    - nodes/stats
    - nodes/proxy`

3. Then restart wandb-console 
4. No error reported in console logs and wandb app.

{"level":"INFO","time":"2024-10-07T07:26:18.708617799Z","info":{"program":"gorilla","source":"github.com/wandb/core/services/gorilla/api/handler/relay.go:263","pid":1062},"data":{"dd.service":"gorilla","dd.version":"84e77719c0b18a6ee8ba2750b4f9abad7fc12286","authUser":"aman","userID":6,"authUser":"aman","userID":6,"operationName":"SecureStorageConnectorEnabled","withAdminPrivileges":true,"defaultEntityID":6,"latencyNs":477712,"statusCode":200,"operationName":"SecureStorageConnectorEnabled","authUser":"aman","variables":{},"latencyStr":"477.712µs"},"message":"Graphql operation SecureStorageConnectorEnabled for user aman with variables map[] finished in 477.712µs","dd.trace_id":"10223050220714882791"}


Let us know where exactly you are facing this issue?

**Comment by danielpanzella** [comment] 2024-10-07 14:13
> I tested with the most recent Operator v1.14.0...those errors are from the operator log, so the issue has to do with operator not operator-wandb

@vijay-wandb This is an incorrect statement.  The issue is that you manually removed permissions from operator's role, so it can now not grant those permissions to the `wandb-console` role.  @amanpruthi removed the node permissions request from operator-wandb [here](https://github.com/wandb/helm-charts/commit/43982fb6e0f90a673cc77e50ce895c0c9b117d01), can you please confirm you are testing with `operator-wandb` chart later than `0.18.1`

**Comment by amanpruthi** [comment] 2024-10-08 15:46
As discussed with @vijay-wandb the issue is now solved and we are closing this

**Closed by amanpruthi** 2024-10-08 15:46 UTC
Labels: enhancement, operator

**Comment by vijay-wandb** [comment] 2024-10-08 15:54
Thank you very much Aman and Aastha for hopping on a call and resolving the problem.
The release channel is mapped to `operator-wandb-0.17.9`, and my testing used this default chart. I'm good now after manually pointing to the latest chart.
